name = "health-connect-mcp"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "health-connect"
database_id = "03a049f9-3c55-48c3-8a53-7fc32baf4bcb"
